# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 46) do

  create_table "affiliate_logs", :force => true do |t|
    t.column "affiliate_id", :integer
    t.column "ip_addr",      :string
    t.column "created_at",   :datetime
  end

  create_table "affiliates", :force => true do |t|
    t.column "name",       :string
    t.column "created_on", :date
  end

  create_table "billings", :force => true do |t|
    t.column "user_id",       :integer
    t.column "billed_on",     :date
    t.column "amount_billed", :integer
    t.column "status",        :boolean
    t.column "response",      :text
    t.column "error_msg",     :string
  end

  create_table "email_clickthrough_stats", :force => true do |t|
    t.column "sent_to_id", :integer
    t.column "email_id",   :integer
    t.column "ip_addr",    :string
    t.column "created_at", :datetime
  end

  create_table "email_open_stats", :force => true do |t|
    t.column "sent_to_id", :integer
    t.column "email_id",   :integer
    t.column "ip_addr",    :string
    t.column "created_at", :datetime
  end

  create_table "emails", :force => true do |t|
    t.column "name",            :string
    t.column "recipient_count", :integer
    t.column "sent_at",         :datetime
    t.column "updated_at",      :datetime
    t.column "created_at",      :datetime
    t.column "email_list",      :string
  end

  create_table "favorite_recipes", :force => true do |t|
    t.column "user_id",    :integer
    t.column "recipe_id",  :integer
    t.column "created_at", :datetime
  end

  create_table "ingredient_categories", :force => true do |t|
    t.column "name", :string
  end

  create_table "ingredients", :force => true do |t|
    t.column "name",                   :string
    t.column "created_at",             :datetime
    t.column "ingredient_category_id", :integer
  end

  create_table "meal_plan_recipes", :force => true do |t|
    t.column "meal_plan_id", :integer
    t.column "recipe_id",    :integer
    t.column "created_at",   :datetime
    t.column "position",     :integer
  end

  create_table "meal_plan_types", :force => true do |t|
    t.column "name", :string
  end

  create_table "meal_plans", :force => true do |t|
    t.column "name",                :string
    t.column "created_at",          :datetime
    t.column "weekly_meal_plan_id", :integer
    t.column "meal_plan_type_id",   :integer
    t.column "note_tip",            :string
  end

  create_table "newsletter_subscribers", :force => true do |t|
    t.column "email",      :string
    t.column "created_at", :datetime
  end

  create_table "newsletters", :force => true do |t|
    t.column "created_on",         :date
    t.column "available_on",       :date
    t.column "sent",               :boolean
    t.column "tip_name",           :string
    t.column "tip_description",    :text
    t.column "treat_name",         :string
    t.column "treat_ingredients",  :text
    t.column "treat_instructions", :text
    t.column "email_greeting",     :string
    t.column "email_question",     :text
    t.column "email_response",     :text
  end

  create_table "promos", :force => true do |t|
    t.column "name",                  :string
    t.column "price",                 :integer
    t.column "days_to_first_billing", :integer
  end

  create_table "recipe_ingredients", :force => true do |t|
    t.column "recipe_id",      :integer
    t.column "ingredient_id",  :integer
    t.column "quantity",       :string
    t.column "measure",        :string
    t.column "notes",          :string
    t.column "alternate",      :string
    t.column "created_at",     :datetime
    t.column "position",       :integer
    t.column "shopping_notes", :text
  end

  create_table "recipes", :force => true do |t|
    t.column "name",         :string
    t.column "instructions", :text
    t.column "notes",        :text
    t.column "servings",     :string
    t.column "created_at",   :datetime
  end

  create_table "referral_logs", :force => true do |t|
    t.column "user_id",    :integer
    t.column "ip_addr",    :string
    t.column "created_at", :datetime
  end

  create_table "referrals", :force => true do |t|
    t.column "referrer_id", :integer
    t.column "referred_id", :integer
    t.column "created_at",  :datetime
    t.column "paid_on",     :date
  end

  create_table "referrer_logs", :force => true do |t|
    t.column "referrer_id", :integer
    t.column "ip_addr",     :string
    t.column "uri",         :string
    t.column "created_at",  :datetime
  end

  create_table "referrers", :force => true do |t|
    t.column "host",       :string
    t.column "created_on", :date
  end

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data",       :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["session_id"], :name => "sessions_session_id_index"

  create_table "site_configurations", :force => true do |t|
    t.column "name",  :string
    t.column "value", :text
  end

  create_table "survey_responders", :force => true do |t|
    t.column "email", :string
  end

  create_table "user_logs", :force => true do |t|
    t.column "user_id",    :integer
    t.column "ip_addr",    :string
    t.column "created_at", :datetime
  end

  create_table "users", :force => true do |t|
    t.column "first_name",            :string
    t.column "last_name",             :string
    t.column "email",                 :string
    t.column "address",               :string
    t.column "city",                  :string
    t.column "state",                 :string
    t.column "phone",                 :string
    t.column "zip",                   :string
    t.column "hash_password",         :string
    t.column "cc_exp",                :date
    t.column "ccnum",                 :string
    t.column "checkacct",             :string
    t.column "last_billing_response", :text
    t.column "billing_info",          :string
    t.column "created_at",            :datetime
    t.column "admin",                 :boolean,               :default => false
    t.column "price",                 :integer
    t.column "next_billing_on",       :date
    t.column "referrer",              :string
    t.column "affiliate_id",          :string
    t.column "cancelled_on",          :date
    t.column "cancel_reason",         :text
    t.column "send_weekly_reminder",  :boolean,               :default => true
    t.column "layout_used",           :string
    t.column "routing_number",        :string
    t.column "recurrence",            :string,                :default => "monthly"
    t.column "viral_sent_count",      :integer,               :default => 0
    t.column "last_billed_on",        :date
    t.column "last_login_at",         :datetime
    t.column "is_affiliate",          :integer,  :limit => 4, :default => 0
    t.column "user_name",             :string
    t.column "failed_notice_count",   :integer
    t.column "on_hold",               :boolean
    t.column "sub_affiliate_id",      :string
  end

  create_table "weekly_meal_plans", :force => true do |t|
    t.column "week_number", :integer
    t.column "created_at",  :datetime
  end

end
